Define 10 UDTs
xyzdelete/PFMCPP_Project3 pull request #1
Opened 2022-10-31 21:13 UTC by xyzdelete

2022-11-01 01:10 UTC, matkatmusic approved these changes

2022-11-03 06:05 UTC, matkatmusic requested changes

2022-11-03 06:05 UTC, matkatmusic commented on main.cpp
> +    int age;
provide a default value for the age.  `0` is fine
- [ ] revise

2022-11-03 06:05 UTC, matkatmusic commented on main.cpp
> +        void burnFuel();
What sort of parameters might these actions depend on? 
perhaps the amount of fuel..
the nozzle size..
Think of that when populating the function parameter lists
- [ ] revise

2022-11-03 06:05 UTC, matkatmusic commented on main.cpp
> +    void regulateVoltage();
what's the input voltage range? 
these should be your function parameters
- [ ] revise

2022-11-03 06:05 UTC, matkatmusic commented on main.cpp
> +    bool convertCurrent(); // returns true if the current has been converted successfully and false otherwise
what voltage is this current at?  how many amps? 
What are you converting it to? 
- [ ] revise

2022-11-04 10:58 UTC, xyzdelete commented on main.cpp
> +    int age;
Done.

2022-11-04 10:58 UTC, xyzdelete commented on main.cpp
> +        void burnFuel();
Done.

2022-11-04 10:58 UTC, xyzdelete commented on main.cpp
> +    void regulateVoltage();
Done.

2022-11-04 10:59 UTC, xyzdelete commented on main.cpp
> +    bool convertCurrent(); // returns true if the current has been converted successfully and false otherwise
Done.

2022-11-04 15:45 UTC, matkatmusic approved these changes

2022-11-04 15:45 UTC, merged